- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  class: "icon-mail"
  title: "Contact"

- name: "RSS"
  url: "/feed.xml"
  class: "icon-rss"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  class: "icon-rss"
  title: "Subscribe to Atom Feed"

- name: "Blog Archive"
  url: "/blog/archive/categoryview"
  class: "icon-archive"
  title: "See all blog post"
